/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import dao.UserDAO;
import models.User;
import models.RegularUser;
import models.AdminUser;
/**
 *
 * @author Nice
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        openPw.setContentAreaFilled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        banner = new javax.swing.JPanel();
        sideBanner = new javax.swing.JLabel();
        formLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        usernameTxtF = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        passwordTxtF = new javax.swing.JPasswordField();
        masukBtn = new javax.swing.JButton();
        openPw = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        createAccLbl = new javax.swing.JLabel();
        createAccLbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));

        banner.setBackground(new java.awt.Color(255, 255, 255));

        sideBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_side_banner.png"))); // NOI18N
        sideBanner.setToolTipText("");
        sideBanner.setAlignmentY(0.0F);

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 732, Short.MAX_VALUE)
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formLogin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Let’s get you back in!");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Continue your creative journey.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoPixelPaint.png"))); // NOI18N
        jLabel2.setText(" ixelPaint");

        usernameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameLbl.setText("Username:");

        usernameTxtF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        usernameTxtF.addActionListener(this::usernameTxtFActionPerformed);

        passwordLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordLbl.setText("Password: ");

        passwordTxtF.setEchoChar('\u25cf');
        passwordTxtF.addActionListener(this::passwordTxtFActionPerformed);

        masukBtn.setBackground(new java.awt.Color(51, 102, 255));
        masukBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        masukBtn.setForeground(new java.awt.Color(255, 255, 255));
        masukBtn.setText("Come In");
        masukBtn.setToolTipText("");
        masukBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masukBtn.addActionListener(this::masukBtnActionPerformed);

        openPw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eyesIcon.png"))); // NOI18N
        openPw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openPw.addActionListener(this::openPwActionPerformed);

        errorLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout formLoginLayout = new javax.swing.GroupLayout(formLogin);
        formLogin.setLayout(formLoginLayout);
        formLoginLayout.setHorizontalGroup(
            formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLoginLayout.createSequentialGroup()
                .addGroup(formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLoginLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(formLoginLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2))
                    .addGroup(formLoginLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(formLoginLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLoginLayout.createSequentialGroup()
                        .addComponent(errorLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(formLoginLayout.createSequentialGroup()
                        .addGroup(formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(masukBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernameTxtF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formLoginLayout.createSequentialGroup()
                                .addComponent(passwordTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openPw, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formLoginLayout.createSequentialGroup()
                                .addGroup(formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordLbl)
                                    .addComponent(usernameLbl))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))))
        );
        formLoginLayout.setVerticalGroup(
            formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLoginLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(usernameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(openPw, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(passwordTxtF, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(masukBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(errorLabel))
        );

        createAccLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        createAccLbl.setText("New here? Create an");

        createAccLbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        createAccLbl1.setForeground(new java.awt.Color(0, 0, 255));
        createAccLbl1.setText("account!");
        createAccLbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccLbl1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createAccLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createAccLbl1)
                        .addGap(30, 30, 30))))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createAccLbl)
                    .addComponent(createAccLbl1))
                .addGap(65, 65, 65)
                .addComponent(formLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private boolean isPasswordVisible = false;
    private void openPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPwActionPerformed
        // TODO add your handling code here:
        if (isPasswordVisible) {
            passwordTxtF.setEchoChar('\u25CF');
        } else {
            passwordTxtF.setEchoChar((char) 0);
        }
        isPasswordVisible = !isPasswordVisible;
    }//GEN-LAST:event_openPwActionPerformed

    private void masukBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukBtnActionPerformed
        // TODO add your handling code here:
        String username = usernameTxtF.getText().trim();
        String password = new String(passwordTxtF.getPassword()).trim();

        if (username.isEmpty() || password.isEmpty()) {
            errorLabel.setText("* Username dan password tidak boleh kosong!");
            errorLabel.setForeground(java.awt.Color.RED);
            return;
        }

        UserDAO userDAO = new UserDAO();
        User user = userDAO.login(username, password);

        if (user != null) {
            if (user.getRole().equals("admin")) {
                ManageFrame manageFrame = new ManageFrame((AdminUser) user);
                manageFrame.setVisible(true);
            } else {
                HomeFrame homeFrame = new HomeFrame(true, user.getId(), user.getUsername());
                homeFrame.setVisible(true);
            }
            this.dispose();
        } else {
            errorLabel.setText("* Username atau password salah!");
            errorLabel.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_masukBtnActionPerformed

    private void createAccLbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccLbl1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new views.RegisterFrame().setVisible(true);
    }//GEN-LAST:event_createAccLbl1MouseClicked

    private void usernameTxtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtFActionPerformed
        // TODO add your handling code here:
        masukBtnActionPerformed(evt);
    }//GEN-LAST:event_usernameTxtFActionPerformed

    private void passwordTxtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtFActionPerformed
        // TODO add your handling code here:
        masukBtnActionPerformed(evt);
    }//GEN-LAST:event_passwordTxtFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel banner;
    private javax.swing.JLabel createAccLbl;
    private javax.swing.JLabel createAccLbl1;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel formLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton masukBtn;
    private javax.swing.JButton openPw;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTxtF;
    private javax.swing.JLabel sideBanner;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTxtF;
    // End of variables declaration//GEN-END:variables
}
