/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import java.sql.*;
import database.DBConnection;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.nio.file.Files;
import java.io.IOException; 
import java.util.List;
import javax.swing.JFileChooser;
import models.GalleryProvider;
import models.Wallpaper;
import javax.swing.JPanel;
import java.awt.*;
import java.nio.file.StandardCopyOption;
import models.WallpaperPrivate;
/**
 *
 * @author Nice
 */
public class ProfileFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProfileFrame.class.getName());

    /**
     * Creates new form ProfileFrame
     */
    private final int currentUserId; 
    private final String currentUsername;
    
    public ProfileFrame(int userId, String username, String bio) {
        this.currentUserId = userId; 
        this.currentUsername = username;
    
        initComponents(); 
      
        
        JPanel wrapper = new JPanel(new BorderLayout());
        
        wrapper.setBackground(jPanel1.getBackground());
        wrapper.add(jPanel1, BorderLayout.NORTH);
        jScrollPaneWallpaperGallery.setViewportView(wrapper);
        
        showGalleryWallpaperUser();       
        jLabelName.setText(username);
        jLabelBio.setText(bio);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProfileInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelBio = new javax.swing.JLabel();
        jButtonUploadImage = new javax.swing.JButton();
        jScrollPaneWallpaperGallery = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile Page");
        setPreferredSize(new java.awt.Dimension(1080, 412));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("WELCOME");

        jLabelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelName.setText("name");

        jLabelBio.setText("bio");
        jLabelBio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonUploadImage.setText("Upload");
        jButtonUploadImage.addActionListener(this::jButtonUploadImageActionPerformed);

        javax.swing.GroupLayout jPanelProfileInfoLayout = new javax.swing.GroupLayout(jPanelProfileInfo);
        jPanelProfileInfo.setLayout(jPanelProfileInfoLayout);
        jPanelProfileInfoLayout.setHorizontalGroup(
            jPanelProfileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfileInfoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelProfileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelProfileInfoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 772, Short.MAX_VALUE)
                .addComponent(jButtonUploadImage)
                .addGap(30, 30, 30))
        );
        jPanelProfileInfoLayout.setVerticalGroup(
            jPanelProfileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfileInfoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelProfileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanelProfileInfoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButtonUploadImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelProfileInfo, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPaneWallpaperGallery.setViewportView(jPanel1);

        getContentPane().add(jScrollPaneWallpaperGallery, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadImageActionPerformed
        // TODO add your handling code here: 
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg"));
        int result = fileChooser.showOpenDialog(this); 

        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File sourceFile = fileChooser.getSelectedFile();
        File targetDirectory = new File("src/uploads"); 

        if (!targetDirectory.exists()) {
            targetDirectory.mkdirs(); 
        }

        long timestamp = System.currentTimeMillis();
        String changedFileName = sourceFile.getName().replace(" ", "_");
        String uniqueFileName = currentUserId + "_" + timestamp + "_" + changedFileName;
        File destinationFile = new File(targetDirectory, uniqueFileName);

        try {
            String title = JOptionPane.showInputDialog(this, "Masukkan Judul Wallpaper:");
            String description = JOptionPane.showInputDialog(this, "Masukkan Deskripsi:");
            String category = JOptionPane.showInputDialog(this, "Masukkan Kategori :");

            if (title == null || category == null) {
                JOptionPane.showMessageDialog(this, "Wallpaper harus diberikan title dan Category!!");
                return;
            }

            // Proses copy file secara langsung ke folder uploads
            Files.copy(sourceFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);

            String insertQuerySQL = "INSERT INTO artworks (title, description, category, image_path, user_id) VALUES (?, ?, ?, ?, ?)";
            try (Connection con = DBConnection.getConnection();
                PreparedStatement AddWallapaperPstmt = con.prepareStatement(insertQuerySQL)) {

                AddWallapaperPstmt.setString(1, title);
                AddWallapaperPstmt.setString(2, description);
                AddWallapaperPstmt.setString(3, category);
                AddWallapaperPstmt.setString(4, uniqueFileName); 
                AddWallapaperPstmt.setInt(5, currentUserId);
                AddWallapaperPstmt.executeUpdate();
            }

            showGalleryWallpaperUser();
            JOptionPane.showMessageDialog(this, "Wallpaper berhasil diunggah!");

        } catch (IOException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memproses unggahan: " + e.getMessage());
        }   
    }//GEN-LAST:event_jButtonUploadImageActionPerformed

    public void showGalleryWallpaperUser() {
        
        jPanel1.removeAll();
        jPanel1.setLayout(new java.awt.GridLayout(0, 5, 15, 15));
        
        //wallpaper private atau public
        GalleryProvider gallery = new WallpaperPrivate();
        
        List<Wallpaper> daftarWallpaper = gallery.getGalleryWallpaper(currentUserId);

        for (Wallpaper wp : daftarWallpaper) {
            WallpaperCard card = new WallpaperCard(wp, currentUserId ,currentUsername, this);
            jPanel1.add(card);
        }

        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProfileFrame(2,"Alvin","coba").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUploadImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBio;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelProfileInfo;
    private javax.swing.JScrollPane jScrollPaneWallpaperGallery;
    // End of variables declaration//GEN-END:variables
}
